apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exploit
  name: exploit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exploit
  template:
    metadata:
      labels:
        app: exploit
    spec:
      containers:
      - image: micahhausler/reinforce-grc302-exploit
        imagePullPolicy: Always
        name: exploit
        command:
        - /bin/sh
        - -c
        - /usr/local/bin/exploit.sh
